wisata/user/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from wisata import app
from wisata.models import Twisata, Tsejarah, Tprofil, Tadmin, Tadat_budaya

guser= Blueprint('guser',__name__)

@guser.route("/")
def home():
    return render_template("t_user/branda.html")

@guser.route("/wisata_alam")
def wisata_alam():
    form=Twisata.query.all()
    return render_template("t_user/wisata_alam.html", form=form)

@guser.route("/galery")
def galery():
    return render_template("t_user/galery.html")

@guser.route("/galery_wisata")
def galery_wisata():
    data=Twisata.query.all()
    return render_template("t_user/galery_wisata.html", data=data)

@guser.route("/galery_sejarah")
def galery_sejarah():
    data=Tsejarah.query.all()
    return render_template("t_user/galery_sejarah.html", data=data)

@guser.route("/galery_adatbudaya")
def galery_adatbudaya():
    data=Tadat_budaya.query.all()
    return render_template("t_user/galery_sejarah.html", data=data)

@guser.route("/sejarah")
def sejarah():
    form=Tsejarah.query.all()
    return render_template("t_user/sejarah.html", form=form)

@guser.route("/dataadat_budaya", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/dataadat_budaya/<int:page>", methods=['GET', 'POST'])
def adat_budaya(page):
    page = page
    pages = 3
    DataAdatBudaya = Tadat_budaya.query.order_by(Tadat_budaya.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        DataAdatBudaya = Tadat_budaya.query.filter(Tadat_budaya.nama.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user/adatbudaya.html", DataAdatBudaya=DataAdatBudaya, tag=tag)
    return render_template("t_user/adatbudaya.html", DataAdatBudaya=DataAdatBudaya )

@guser.route("/contact")
def contac():
    return render_template("t_user/contact.html")


#route untuk ketegangan
@guser.route("/keterangan_wisata/<int:ed_id>/wisata", methods=['GET', 'POST'])
def keterangan_wisata(ed_id):
    dt=Twisata.query.get_or_404(ed_id)
    return render_template('t_user/keterangan.html',dt=dt)

@guser.route("/keterangansejarah/<int:ed_id>/sejarah", methods=['GET', 'POST'])
def keterangansejarah(ed_id):
    dt=Tsejarah.query.get_or_404(ed_id)
    return render_template('t_user/keterangan_sejarah.html',dt=dt)

@guser.route("/keteranganadatbudaya/<int:ed_id>/kebudayaan", methods=['GET', 'POST'])
def keteranganadatbudaya(ed_id):
    dt=Tadat_budaya.query.get_or_404(ed_id)
    return render_template('t_user/keteranga_adat_budaya.html',dt=dt)
#akhir route keterangan

wisata/templates/t_user/contact.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="generator" content="">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
	<!-- <link href="../../static/css layout/css/style.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/style.css')}}">
	<link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/animate.css')}}">
	<link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
	<link href="{{ url_for ('static', filename='css layout/css/prettyPhoto.css')}}" rel="stylesheet">
	<link href="{{ url_for ('static', filename='css layout/js/google-code-prettify/prettify.css')}}" rel="stylesheet">
	<link href="{{ url_for ('static', filename='css layout/css/flexslider.css')}}" rel="stylesheet">
	<title>CONTACT</title>
	<link rel="icon" type="css layout/images/logo.png"
		href="{{ url_for ('static', filename='css layout/images/logo.png')}}">
</head>

<body>

	<!-- HEADER =============================-->
	<header class="item header_ margin-top-0">
		<div class="wrapper">
			<nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
				<div class="container">
					<div class="navbar-header">
						<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
							<i class="fa fa-bars"></i>
							<span class="sr-only">Toggle navigation</span>
						</button>
						<a href="index.html" class="navbar-brand brand"> SCORILO </a>
					</div>
					<div id="navbar-collapse-02" class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.home')}}">Beranda</a></li>
							<li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.sejarah')}}">Sejarah</a></li>
							<li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.wisata_alam')}}">Wisata</a></li>
							<li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.adat_budaya')}}">Adat & Budaya</a>
							</li>
							<li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.galery')}}">Galery</a></li>
							<li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.contac')}}">Contact</a></li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="container">
				<div class="row">
					<div class="col-md-12 text-center">
						<div class="text-homeimag">
							<div class="maintext-image" data-scrollreveal="enter top over 1.5s after 0.1s">
								Contact
							</div>
							<div class="subtext-image" data-scrollreveal="enter bottom over 1.7s after 0.3s">
								<h4 class="text-uppercase"></h4>
							</div>
						</div>
					</div>
				</div>
			</div>
	</header>
	<!-- CONTENT =============================-->
	<section class="item content">
		<div class="container toparea">
			<div class="underlined-title">
				<div class="editContent">
					<h1 class="text-center latestitems">Get in Touch</h1>
				</div>
				<div class="wow-hr type_short">
					<span class="wow-hr-h">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
					</span>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="done">
						<div class="alert alert-success">
							<button type="button" class="close" data-dismiss="alert">×</button>
							Your message has been sent. Thank you!
						</div>
					</div>
					<form method="post" action="contact.php" id="contactform">
						<div class="form">
							<input type="text" name="name" placeholder="Your Name *">
							<input type="text" name="email" placeholder="Your E-mail Address *">
							<textarea name="comment" rows="7" placeholder="Type your Message *"></textarea>
							<input type="submit" id="submit" class="clearfix btn" value="Send">
						</div>
					</form>
				</div>
			</div>
		</div>
		</div>
	</section>
	<!-- CALL TO ACTION =============================-->
	<section class="content-block" style="background-color:#00bba7;">
		<div class="container text-center">
			<div class="row">
				<div class="col-sm-10 col-sm-offset-1">
					<div class="item" data-scrollreveal="enter top over 0.4s after 0.1s">
						<h1 class="callactiontitle"> Promote Items Area Give Discount to Buyers <span class="callactionbutton"><i
									class="fa fa-gift"></i> WOW24TH</span>
						</h1>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- FOOTER =============================-->
	<div class="footer text-center">
		<div class="container">
			<div class="row">
				<p class="footernote">
					Connect with Dinas Kebudayaan & Pariwisata
				</p>
				<ul class="social-iconsfooter">
					<li><a href="#"><i class="fa fa-phone"></i></a></li>
					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
				</ul>
				<p>
					&copy; dinas kebudayaan dan pariwisata<br />
					<!-- Scorilo - Free template by <a href="https://www.wowthemes.net/">WowThemesNet</a> -->
				</p>
			</div>
		</div>
	</div>
	<!-- SCRIPTS =============================-->
	<script src="{{ url_for ('static', filename='css layout/js/jquery-.js')}}"></script>
	<script src="{{ url_for ('static', filename='css layout/js/bootstrap.min.js')}}"></script>
	<script src="{{ url_for ('static', filename='css layout/js/anim.js')}}"></script>
	<script src="{{ url_for ('static', filename='css layout/js/validate.js')}}"></script>
	<script src="js/validate.js"></script>
</body>

</html>

wisata/templates/t_user/galery.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="generator" content="">
  <!-- <link href="../../static/css layout/css/bootstrap.min.css" rel="stylesheet"> -->

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <!-- <link href="../../static/css layout/css/style.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/style.css')}}">
  <link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/animate.css')}}">
  <link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
  <link href="{{ url_for ('static', filename='css layout/css/prettyPhoto.css')}}" rel="stylesheet">
  <link href="{{ url_for ('static', filename='css layout/js/google-code-prettify/prettify.css')}}" rel="stylesheet">
  <link href="{{ url_for ('static', filename='css layout/css/flexslider.css')}}" rel="stylesheet">
  <title>GALERY</title>
  <link rel="icon" type="css layout/images/logo.png"
    href="{{ url_for ('static', filename='css layout/images/logo.png')}}">
</head>

<body>


  <!-- HEADER =============================-->
  <header class="item header_ margin-top-0">
    <div class="wrapper">
      <nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle navigation</span>
            </button>
            <a href="{{url_for('guser.home')}}" class="navbar-brand brand"> Disbudpar Tikep </a>
          </div>
          <div id="navbar-collapse-02" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.home')}}">Beranda</a></li>
              <li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.sejarah')}}">Sejarah</a></li>
              <li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.wisata_alam')}}">Wisata</a></li>
              <li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.adat_budaya')}}">Adat & Budaya</a>
              </li>
              <li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.galery')}}">Galery</a></li>
              <li class="propClone btn-large e_wiggle"><a href="{{url_for('guser.contac')}}">Contact</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="text-homeimag">
              <div class="maintext-image" data-scrollreveal="enter top over 1.5s after 0.1s">
                Dinas pariwisata
              </div>
              <div class="subtext-image" data-scrollreveal="enter bottom over 1.7s after 0.3s">
                Kota Tidore Kepulauan
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- LATEST ITEMS =============================-->
  <section class="item content">
    <div class="container">
      <div class="underlined-title">
        <div class="editContent">
          <h1 class="text-center latestitems">LITS GALERY ITEMS</h1>
        </div>
        <div class="wow-hr type_short">
          <span class="wow-hr-h">
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
          </span>
        </div>
      </div>
      <div class="row">
        <!-- Galery wisata -->
        <div class="col-md-4" data-scrollreveal="enter top over 1.5s after 0.1s">
          <div class="productbox">
            <div class="fadeshop">
              <div class="captionshop text-center" style="display: none;">
                <h3>GALERY</h3>
                <p>
                  klik di sini untuk melihat gambar wisata tidore kepulauan
                </p>
                <p>
                  <a href="{{url_for('guser.galery_wisata')}}" class="learn-more detailslearn"><i
                      class="fa fa-link"></i> Details</a>
                </p>
              </div>
              <span class="maxproduct"><img src="{{ url_for ('static', filename='css layout/images/product2.jpg')}}"
                  alt=""></span>
            </div>
            <div class="product-details">
              <a href="#">
                <h1>wisata</h1>
              </a>
            </div>
          </div>
        </div>
        <!-- akhir galery wisata -->

        <!-- galery sejarah-->
        <div class="col-md-4" data-scrollreveal="enter top over 1.5s after 0.1s">
          <div class="productbox">
            <div class="fadeshop">
              <div class="captionshop text-center" style="display: none;">
                <h3>GALERY</h3>
                <p>
                  klik di sini untuk melihat gambar gambar sejarah tidore kepulauan
                </p>
                <p>
                  <a href="{{url_for('guser.galery_sejarah')}}" class="learn-more detailslearn"><i
                      class="fa fa-link"></i> Details</a>
                </p>
              </div>
              <span class="maxproduct"><img src="{{ url_for ('static', filename='css layout/images/product3.jpg')}}"
                  alt=""></span>
            </div>
            <div class="product-details">
              <a href="">
                <h1>Sejarah</h1>
              </a>
            </div>
          </div>
        </div>
        <!-- akhir galery sejaraj -->

        <!-- Galery adat budaya -->
        <div class="col-md-4" data-scrollreveal="enter top over 1.5s after 0.1s">
          <div class="productbox">
            <div class="fadeshop">
              <div class="captionshop text-center" style="display: none;">
                <h3>GALERY</h3>
                <p>
                  klik di sini untuk melihat gambar adat dan budaya tidore kepulauan
                </p>
                <p>
                  <a href="{{url_for('guser.galery_adatbudaya')}}" class="learn-more detailslearn"><i
                      class="fa fa-link"></i> Details</a>
                </p>
              </div>
              <span class="maxproduct"><img src="{{ url_for ('static', filename='css layout/images/product2.jpg')}}"
                  alt=""></span>

            </div>
            <div class="product-details">
              <a href="#">
                <h1>Adat Dan Budaya</h1>
              </a>
            </div>
          </div>
        </div>
        <!-- akhir galery adat budaya -->
      </div>
    </div>
    </div>
  </section>


  <!-- BUTTON =============================-->
  <div class="item content">
    <!-- <div class="container text-center">
      <a href="shop.html" class="homebrowseitems">Browse All Products
        <div class="homebrowseitemsicon">
          <i class="fa fa-star fa-spin"></i>
        </div>
      </a>
    </div>
  </div>
  <br /> -->


    <!-- TESTIMONIAL =============================-->
    <div class="item content">
      <div class="container">
        <div class="col-md-10 col-md-offset-1">
          <div class="slide-text">
            <div>
              <h2><span class="uppercase">Awesome Support</span></h2>
              <img src="http://wowthemes.net/demo/salique/salique-boxed/images/temp/avatar2.png" alt="Awesome Support">
              <p>
                The support... I can only say it's awesome. You make a product and you help people out any way you can
                even if it means that you have to log in on their dashboard to sort out any problems that customer might
                have. Simply Outstanding!
              </p>
              <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                class="fa fa-star"></i>
            </div>
          </div>
        </div>
      </div>
    </div>


    <!-- CALL TO ACTION =============================-->
    <section class="content-block" style="background-color:#00bba7;">
      <div class="container text-center">
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <div class="item" data-scrollreveal="enter top over 0.4s after 0.1s">
              <h1 class="callactiontitle"> Promote Items Area Give Discount to Buyers <span class="callactionbutton"><i
                    class="fa fa-gift"></i> WOW24TH</span>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </section>


    <!-- FOOTER =============================-->
    <div class="footer text-center">
      <div class="container">
        <div class="row">
          <p class="footernote">
            Connect with Dinas Kebudayaan & Pariwisata
          </p>
          <ul class="social-iconsfooter">
            <li><a href="#"><i class="fa fa-phone"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
          </ul>
          <p>
            &copy; dinas kebudayaan dan pariwisata<br />
            <!-- Scorilo - Free template by <a href="https://www.wowthemes.net/">WowThemesNet</a> -->
          </p>
        </div>
      </div>
    </div>

    <!-- SCRIPTS =============================-->
    <script src="{{ url_for ('static', filename='css layout/js/jquery-.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/anim.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/animate.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery-hover-effect.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/raphael-min.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery.easing.1.3.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/bootstrap.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/google-code-prettify/prettify.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery.elastislide.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery.prettyPhoto.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery.flexslider.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/jquery-hover-effect.js')}}"></script>
    <script src="{{ url_for ('static', filename='css layout/js/animate.js')}}"></script>

    <!-- Template Custom JavaScript File -->
    <script src="assets/js/custom.js"></script>

    <script>
      //----HOVER CAPTION---//	  
      jQuery(document).ready(function ($) {
        $('.fadeshop').hover(
          function () {
            $(this).find('.captionshop').fadeIn(150);
          },
          function () {
            $(this).find('.captionshop').fadeOut(150);
          }
        );
      });
    </script>

</body>

</html>

wisata/templates/t_user/galery_wisata.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="generator" content="">
	<!-- <link href="../../static/css layout/css/bootstrap.min.css" rel="stylesheet"> -->

	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
	<!-- <link href="../../static/css layout/css/style.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{ url_for ('static', filename='css layout/css/style.css')}}">
	<link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
	<title>GALERY WISATA</title>
	<link rel="icon" type="css layout/images/logo.png"
		href="{{ url_for ('static', filename='css layout/images/logo.png')}}">
</head>

<body>


	<!-- HEADER =============================-->
	<header class="item header_ margin-top-0">
		<div class="wrapper">
			<nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
				<div class="container">
					<div class="navbar-header">
						<button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
							<i class="fa fa-bars"></i>
							<span class="sr-only">Toggle navigation</span>
						</button>
						<a href="{{url_for('guser.home')}}" class="navbar-brand brand"> wondelrul tidore </a>
					</div>
					<div id="navbar-collapse-02" class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li class="propClone"><a href="{{url_for('guser.home')}}">Beranda</a></li>
							<li class="propClone"><a href="{{url_for('guser.sejarah')}}">Sejarah</a></li>
							<li class="propClone"><a href="{{url_for('guser.wisata_alam')}}">Wisata</a></li>
							<li class="propClone"><a href="{{url_for('guser.adat_budaya')}}">Adat & Budaya</a></li>
							<li class="propClone"><a href="{{url_for('guser.galery')}}">Galery</a></li>
							<li class="propClone"><a href="{{url_for('guser.contac')}}">Contact</a></li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="container">
				<div class="row">
					<div class="col-md-12 text-center">
						<div class="text-homeimag">
							<div class="maintext-image" data-scrollreveal="enter top over 1.5s after 0.1s">
								Dinas pariwisata
							</div>
							<div class="subtext-image" data-scrollreveal="enter bottom over 1.7s after 0.3s">
								Galery Wisata
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- LATEST ITEMS =============================-->
	<section class="item content">
		<div class="container">
			<div class="underlined-title">
				<div class="editContent">
					<h1 class="text-center latestitems">All Images Wisata Tidore Kepulauan</h1>
				</div>
				<div class="wow-hr type_short">
					<span class="wow-hr-h">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
					</span>
				</div>
			</div>
			<div class="row">
				<!-- Galery wisata -->
				{%for dta in data%}
				<div class="col-md-3">
					<div class="productbox">
						<div class="fadeshop">
							<span class="maxproduct"><img src="{{ url_for ('static', filename='css layout/images/' + dta.gambar)}}"
									alt="" width="330" height="200"></span>
						</div>
						<div class="product-details">
							<a href="#">
								<h1>{{dta.nama_wisata}}</h1>
							</a>
						</div>
					</div>
				</div>
				{%endfor%}
				<!-- akhir galery adat budaya -->
			</div>
		</div>
		</div>
	</section>


	<!-- BUTTON =============================-->
	<div class="item content">
		<!-- <div class="container text-center">
      <a href="shop.html" class="homebrowseitems">Browse All Products
        <div class="homebrowseitemsicon">
          <i class="fa fa-star fa-spin"></i>
        </div>
      </a>
    </div>
  </div>
  <br /> -->


		<!-- TESTIMONIAL =============================-->
		<div class="item content">
			<div class="container">
				<div class="col-md-10 col-md-offset-1">
					<div class="slide-text">
						<div>
							<h2><span class="uppercase">Awesome Support</span></h2>
							<img src="http://wowthemes.net/demo/salique/salique-boxed/images/temp/avatar2.png" alt="Awesome Support">
							<p>
								The support... I can only say it's awesome. You make a product and you help people out any way you can
								even if it means that you have to log in on their dashboard to sort out any problems that customer might
								have. Simply Outstanding!
							</p>
							<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
								class="fa fa-star"></i>
						</div>
					</div>
				</div>
			</div>
		</div>


		<!-- CALL TO ACTION =============================-->
		<section class="content-block" style="background-color:#00bba7;">
			<div class="container text-center">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="item" data-scrollreveal="enter top over 0.4s after 0.1s">
							<h1 class="callactiontitle"> Promote Items Area Give Discount to Buyers <span class="callactionbutton"><i
										class="fa fa-gift"></i> WOW24TH</span>
							</h1>
						</div>
					</div>
				</div>
			</div>
		</section>


		<!-- FOOTER =============================-->
		<div class="footer text-center">
			<div class="container">
				<div class="row">
					<p class="footernote">
						Connect with Scorilo
					</p>
					<ul class="social-iconsfooter">
						<li><a href="#"><i class="fa fa-phone"></i></a></li>
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
					</ul>
					<p>
						&copy; 2017 Your Website Name<br />
						Scorilo - Free template by <a href="https://www.wowthemes.net/">WowThemesNet</a>
					</p>
				</div>
			</div>
		</div>

		<!-- SCRIPTS =============================-->
		<script src="{{ url_for ('static', filename='css layout/js/jquery-.js')}}"></script>
		<script src="{{ url_for ('static', filename='css layout/js/bootstrap.min.js')}}"></script>
		<script src="{{ url_for ('static', filename='css layout/js/anim.js')}}"></script>

		<script>
			//----HOVER CAPTION---//	  
			jQuery(document).ready(function ($) {
				$('.fadeshop').hover(
					function () {
						$(this).find('.captionshop').fadeIn(150);
					},
					function () {
						$(this).find('.captionshop').fadeOut(150);
					}
				);
			});
		</script>

</body>

</html>