wisata/admin/routes.py
import os 
import secrets
from flask import Flask, render_template, redirect, url_for, request, flash, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from wisata import app, db, bcrypt
from wisata.admin.forms import admin_F, wisata_F, login, sejarah_F, adatbudaya_F, eadmin_F, galery_F, editadatbudaya_F, editsejarah_F, editwisata_F
from wisata.models import Twisata, Tsejarah, Tprofil, Tadmin, Tadat_budaya
from PIL import Image

gadmin= Blueprint('gadmin',__name__)


# route simpam
def simpan_gambar(fotoo):
    random_hex= secrets.token_hex(8)
    _, f_ext= os.path.splitext(fotoo.filename)
    foto_fn= random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'wisata/static/css layout/images', foto_fn)

    ubah_size=(300,300)
    j=Image.open(fotoo)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    return foto_fn
# akhir rote simpan


# awal route wisata
@gadmin.route("/isi_data_wisata", methods=['GET','POST'])
@login_required
def isi_data_wisata():
    form=wisata_F()
    if form.validate_on_submit():
        nama_gambar= simpan_gambar(form.foto.data)
        add = Twisata(nama_wisata=form.nama_wisata.data, keterangan=form.keterangan.data, lokasi=form.lokasi.data, gambar=nama_gambar)
        db.session.add(add)
        db.session.commit()
        flash(f'Data Berhasil Di Input', 'primary')
        return redirect(url_for('gadmin.isi_data_wisata'))
    return render_template("t_admin/wisata.html", form=form)

@gadmin.route("/admin_wisata")
def admin_wisata():
    form=Twisata.query.all()
    return render_template("t_admin/data_wisata.html", form=form)

@gadmin.route("/editwisata/<int:ed_id>/update", methods=['GET', 'POST'])
def update_wisata(ed_id):
    datawisata=Twisata.query.get_or_404(ed_id)
    form=editwisata_F()
    if form.validate_on_submit():
        if form.foto.data:
            nama_gambar= simpan_gambar(form.foto.data)
            datawisata.gambar = nama_gambar
        datawisata.nama_wisata=form.nama_wisata.data
        datawisata.keterangan=form.keterangan.data
        datawisata.lokasi=form.lokasi.data
        db.session.commit()
        flash('Data Berhasil Di ubah','warning')
        return redirect(url_for('gadmin.admin_wisata'))
    elif request.method=="GET":
        form.nama_wisata.data=datawisata.nama_wisata
        form.keterangan.data=datawisata.keterangan
        form.lokasi.data=datawisata.lokasi
    return render_template('t_admin/editwisata.html', form=form)

@gadmin.route("/hapus_wisata/<id>", methods=['GET', 'POST'])
def hapus_wisata(id):
    my_data = Twisata.query.get(id)
    db.session.delete(my_data)
    db.session.commit()
    flash('Data berhasisl dihapus', 'warning')
    return redirect(url_for('gadmin.admin_wisata'))
# akhir route wisata


# awal route sejara
@gadmin.route("/isi_sejarah", methods=['GET','POST'])
@login_required
def isi_sejarah():
    form=galery_F()
    if form.validate_on_submit():
        jjk= simpan_gambar(form.gambar.data)
        add = Tsejarah(nama=form.nama.data, keterangan=form.keterangan.data, gambar=jjk)
        db.session.add(add)
        db.session.commit()
        flash(f'Data Berhasil Di Input', 'primary')
        return redirect(url_for('gadmin.isi_sejarah'))
    return render_template("t_admin/sejarah.html", form=form)

@gadmin.route("/admin_sejarah")
def admin_sejarah():
    form=Tsejarah.query.all()
    return render_template("t_admin/data_sejarah.html", form=form)

@gadmin.route("/editsejarah/<int:ed_id>/update", methods=['GET', 'POST'])
def update_sejarah(ed_id):
    datasejarah=Tsejarah.query.get_or_404(ed_id)
    form=editsejarah_F()
    if form.validate_on_submit():
        if form.foto.data:
            nama_gambar= simpan_gambar(form.foto.data)
            datawisata.gambar = nama_gambar
        datasejarah.nama=form.nama.data
        datasejarah.keterangan=form.keterangan.data
        db.session.commit()
        flash('Data Berhasil Di ubah','warning')
        return redirect(url_for('gadmin.admin_sejarah'))
    elif request.method=="GET":
        form.nama.data=datasejarah.nama
        form.keterangan.data=datasejarah.keterangan
    return render_template('t_admin/editsejarah.html', form=form)

@gadmin.route("/hapus_sejarah/<id>", methods=['GET', 'POST'])
def hapus_sejarah(id):
    my_data = Tsejarah.query.get(id)
    db.session.delete(my_data)
    db.session.commit()
    flash('Data berhasisl dihapus', 'warning')
    return redirect(url_for('gadmin.admin_sejarah'))
# akhir route sejarah


# awal route adat budaya
@gadmin.route("/admin_adatbudaya")
def admin_adatbudaya():
    form=Tadat_budaya.query.all()
    return render_template("t_admin/data_budaya.html", form=form)

@gadmin.route("/hapus_adatbudaya/<id>", methods=['GET', 'POST'])
def hapus_adatbudaya(id):
    H_data = Tadat_budaya.query.get(id)
    db.session.delete(H_data)
    db.session.commit()
    flash('Data berhasisl dihapus', 'warning')
    return redirect(url_for('gadmin.admin_adatbudaya'))


@gadmin.route("/editadatbudaya/<int:ed_id>/update", methods=['GET', 'POST'])
def update_adatbudaya(ed_id):
    dataadatbudaya=Tadat_budaya.query.get_or_404(ed_id)
    form=editadatbudaya_F()
    if form.validate_on_submit():
        if form.foto.data:
            nama_gambar= simpan_gambar(form.foto.data)
            datawisata.gambar = nama_gambar
        dataadatbudaya.nama=form.nama.data
        dataadatbudaya.keterangan=form.keterangan.data
        db.session.commit()
        flash('Data Berhasil Di ubah','warning')
        return redirect(url_for('gadmin.admin_adatbudaya'))
    elif request.method=="GET":
        form.nama.data=dataadatbudaya.nama
        form.keterangan.data=dataadatbudaya.keterangan
    return render_template('t_admin/editadatbudaya.html', form=form)

@gadmin.route("/isi_adatbudaya", methods=['GET','POST'])
@login_required
def isi_adatbudaya():
    form=adatbudaya_F()
    if form.validate_on_submit():
        jjk= simpan_gambar(form.gambar.data)
        add = Tadat_budaya(nama=form.nama.data, keterangan=form.keterangan.data, gambar=jjk)
        db.session.add(add)
        db.session.commit()
        flash(f'Data Berhasil Di Input', 'primary')
        return redirect(url_for('gadmin.isi_adatbudaya'))
    return render_template("t_admin/adatbudaya.html", form=form)
# akhir route adat budaya


# awal rote galery
@gadmin.route("/isi_galery", methods=['GET','POST'])
@login_required
def isi_galery():
    form=sejarah_F()
    if form.validate_on_submit():
        jjk= simpan_gambar(form.gambar.data)
        add = Tsejarah(nama=form.nama.data, keterangan=form.keterangan.data, gambar=jjk)
        db.session.add(add)
        db.session.commit()
        flash(f'Data Berhasil Di Input', 'primary')
        return redirect(url_for('gadmin.isi_galery'))
    return render_template("t_admin/galery.html", form=form)
# akhir route galery


# awal route admin
@gadmin.route("/daftar_admin",  methods=['GET', 'POST'])
@login_required
def daftar_admin():
    form=admin_F()
    if form.validate_on_submit():
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add= Tadmin(nama=form.nama.data, username=form.username.data, password=pass_hash)
        db.session.add(add)
        db.session.commit()
        flash(f'Akun berhasil daftar', 'primary')
        return redirect(url_for('gadmin.daftar_admin'))
    return render_template("t_admin/admin.html",form=form)

@gadmin.route("/login_admin",  methods=['GET', 'POST'])
def login_admin():
    form=login()
    if request.method == 'POST':
        ceknik=Tadmin.query.filter_by(username=form.username.data).first()
        if ceknik and bcrypt.check_password_hash(ceknik.password, form.password.data):
            login_user(ceknik)
            flash('selamat Datang Kembali', 'warning')
            return redirect(url_for('gadmin.daftar_admin'))
        else:
            flash('login gagal, periksa username dan Password!', 'danger')
    return render_template("t_admin/login_admin.html", form=form)

@gadmin.route("/logout_admin")
def logout_admin():
    logout_user()
    return redirect(url_for('gadmin.login_admin'))


@gadmin.route("/admin", methods=['GET', 'POST'])
def admin():
    dataadmin=Tadmin.query.all()
    return render_template("t_admin/tampilan.html", data=dataadmin)

@gadmin.route("/edithakakses/<int:ed_id>/update", methods=['GET', 'POST'])
def update_admin(ed_id):
    dataadmin=Tadmin.query.get_or_404(ed_id)
    form=eadmin_F()
    if form.validate_on_submit():
        cekpass= Tadmin.query.filter_by(username=form.username.data).first()
        if cekpass and bcrypt.check_password_hash(cekpass.password, form.password.data):
            pass_hash= bcrypt.generate_password_hash(form.passwordbaru.data). decode('utf-8')
            dataadmin.username=form.usernamebaru.data
            dataadmin.password=pass_hash
            db.session.commit()
            flash('Hak Akses Berhasil di ubah','warning')
            return redirect(url_for('gadmin.admin'))
        else:
            flash('password yang dimasukan salah, silahkan coba kembali !!','danger')
            return redirect(url_for('gadmin.admin'))
       
    return render_template("t_admin/eadmin.html", data=dataadmin, form=form)
# akhir rote admin




    

wisata/user/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from wisata import app
from wisata.models import Twisata, Tsejarah, Tprofil, Tadmin, Tadat_budaya

guser= Blueprint('guser',__name__)

@guser.route("/")
def home():
    return render_template("t_user/branda.html")

@guser.route("/wisata_alam")
def wisata_alam():
    form=Twisata.query.all()
    return render_template("t_user/wisata_alam.html", form=form)

@guser.route("/galery")
def galery():
    return render_template("t_user/galery.html")

@guser.route("/galery_wisata")
def galery_wisata():
    data=Twisata.query.all()
    return render_template("t_user/galery_wisata.html", data=data)

@guser.route("/galery_sejarah")
def galery_sejarah():
    data=Tsejarah.query.all()
    return render_template("t_user/galery_sejarah.html", data=data)

@guser.route("/galery_adatbudaya")
def galery_adatbudaya():
    data=Tadat_budaya.query.all()
    return render_template("t_user/galery_sejarah.html", data=data)

@guser.route("/sejarah")
def sejarah():
    form=Tsejarah.query.all()
    return render_template("t_user/sejarah.html", form=form)

@guser.route("/dataadat_budaya", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/dataadat_budaya/<int:page>", methods=['GET', 'POST'])
def adat_budaya(page):
    page = page
    pages = 3
    DataAdatBudaya = Tadat_budaya.query.order_by(Tadat_budaya.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        DataAdatBudaya = Tadat_budaya.query.filter(Tadat_budaya.nama.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user/adatbudaya.html", DataAdatBudaya=DataAdatBudaya, tag=tag)
    return render_template("t_user/adatbudaya.html", DataAdatBudaya=DataAdatBudaya )

@guser.route("/contact")
def contac():
    return render_template("t_user/contact.html")


#route untuk ketegangan
@guser.route("/keterangan_wisata/<int:ed_id>/wisata", methods=['GET', 'POST'])
def keterangan_wisata(ed_id):
    dt=Twisata.query.get_or_404(ed_id)
    return render_template('t_user/keterangan.html',dt=dt)

@guser.route("/keterangansejarah/<int:ed_id>/sejarah", methods=['GET', 'POST'])
def keterangansejarah(ed_id):
    dt=Tsejarah.query.get_or_404(ed_id)
    return render_template('t_user/keterangan_sejarah.html',dt=dt)

@guser.route("/keteranganadatbudaya/<int:ed_id>/kebudayaan", methods=['GET', 'POST'])
def keteranganadatbudaya(ed_id):
    dt=Tadat_budaya.query.get_or_404(ed_id)
    return render_template('t_user/keteranga_adat_budaya.html',dt=dt)
#akhir route keterangan

wisata/templates/t_admin/adatbudaya.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>Mengisi data adat dan budaya</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.gambar.label(class="form-control-label")}}
                {{form.gambar(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>

        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='keterangan') }}
    </div>
</div>


</div>
</div>
{%endblock%}

wisata/templates/t_admin/base_login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KEMENTERIAN PARIWISATA & BUDAYA</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="{{ url_for ('static', filename='CSS/css/bootstrap.min.css')}}">
  <link href="{{ url_for ('static', filename='CSS/style.css')}}" rel="stylesheet" type="text/css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="{{ url_for ('static', filename='vendor/fontawesome-free-5.15.3-web/css/all.min.css')}}" rel="stylesheet"
    type="text/css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">

</head>

<body>

  <body>
    <div class="row tengah">
      <div class="col-md-5">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            {% with messages= get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, massage in messages %}

            <div class="alert alert-{{category}}">
              {{massage}}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {%block kontent%}
            {%endblock%}
          </div>
        </div>
      </div>
    </div>




    <!-- jQuery library -->
    <script src="{{ url_for ('static', filename='CSS/css/jquery.min.js')}}"></script>

    <!-- Popper JS -->
    <script src="{{ url_for ('static', filename='CSS/css/popper.min.js')}}"></script>

    <!-- Latest compiled JavaScript -->
    <script src="{{ url_for ('static', filename='CSS/css/bootstrap.min.css')}}"></script>

  </body>

</html>

wisata/templates/t_admin/data_budaya.html
{% extends 't_admin/base.html'%}

{%block konten%}
<div class="row row-cols-1 row-cols-md-3">
  <div class="col-md-4 mb-4">
    <table class="table table-responsive table-hover table-dark">
      <tr>
        <th scope="col">NAMA</th>
        <th scope="col">Edit</th>
        <th scope="col">Hapus</th>
      </tr>
      <tr>
        {%for data in form%}
        <td class="text-uppercase">{{data.nama}}</td>
        <td><a href="{{url_for('gadmin.update_adatbudaya', ed_id=data.id)}}" class="btn btn-warning btn-xs">Edit</a>
        </td>
        <td><a href="/hapus_adatbudaya/{{data.id}}" class="btn btn-danger btn-xs"
            onclick="return confirm('Yakin ingin hapus')">Hapus</a>
        </td>
      </tr>
      <!-- akhir data pengaduan -->

      {%endfor%}
    </table>
  </div>

</div>
{% endblock %}

wisata/templates/t_admin/data_wisata.html
{% extends 't_admin/base.html'%}

{%block konten%}
<div class="row row-cols-1 row-cols-md-3">
	<div class="col-md-4 mb-4">
		<table class="table table-responsive table-hover table-dark">
			<tr>
				<th scope="col">NAMA</th>
				<th scope="col">Edit</th>
				<th scope="col">Hapus</th>
			</tr>
			<tr>
				{%for data in form%}
				<td class="text-uppercase">{{data.nama_wisata}}</td>
				<td><a href="{{url_for('gadmin.update_wisata', ed_id=data.id)}}" class="btn btn-warning btn-xs">Edit</a></td>
				<td><a href="/hapus_wisata/{{data.id}}" class="btn btn-danger btn-xs"
						onclick="return confirm('Yakin ingin hapus')">Hapus</a>
				</td>
			</tr>
			<!-- akhir data pengaduan -->

			{%endfor%}
		</table>
	</div>

</div>
{% endblock %}

wisata/templates/t_admin/eadmin.html
{% extends "t_admin/base.html" %}

{% block konten%}
    
    <!-- Begin Page Content -->
    <div class="container-fluid">
    
                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">Industri</h1>
                            <!--bagian bisa dimasukan form seacrh dari masing-masing data-->
                            <p></p>
                        </div>
    
                        <!-- Content Row -->
                    
                        <div class="row">
    
                            <!-- Data indusrti -->
                            <div class="col-xl-4 col-lg-5">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h6 class="m-0 font-weight-bold text-primary">Ubah Hak Akses</h6>
                                       
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        <!--form inputan-->
                                        <p>bagian untuk meletakan form inputan</p>
                                        <form method="POST">
                                            {{form.hidden_tag()}}

                                        <div class="form-group">
                                            {{form.username.label(class="form-control-label")}}
                                            {% if form.username.errors %}
                                                 {{form.username(class="form-control is-invalid")}}
                                        
                                                 <div class="invalid-feedback">
                                                     {%for error in form.username.errors %}
                                                     <span>{{error}}</span>
                                                     {% endfor %}
                                                 </div>
                                            {%else%}
                                                {{form.username(class="form-control")}}
                                            
                                            {%endif%}
                                        </div>

                                        <div class="form-group">
                                            {{form.password.label(class="form-control-label")}}
                                            {% if form.password.errors %}
                                                 {{form.password(class="form-control is-invalid")}}
                                        
                                                 <div class="invalid-feedback">
                                                     {%for error in form.password.errors %}
                                                     <span>{{error}}</span>
                                                     {% endfor %}
                                                 </div>
                                            {%else%}
                                                {{form.password(class="form-control")}}
                                            
                                            {%endif%}
                                        </div>

                                        <div class="form-group">
                                            {{form.usernamebaru.label(class="form-control-label")}}
                                            {% if form.usernamebaru.errors %}
                                                 {{form.usernamebaru(class="form-control is-invalid")}}
                                        
                                                 <div class="invalid-feedback">
                                                     {%for error in form.usernamebaru.errors %}
                                                     <span>{{error}}</span>
                                                     {% endfor %}
                                                 </div>
                                            {%else%}
                                                {{form.usernamebaru(class="form-control")}}
                                            
                                            {%endif%}
                                        </div>

                                        <div class="form-group">
                                            {{form.passwordbaru.label(class="form-control-label")}}
                                            {% if form.passwordbaru.errors %}
                                                 {{form.passwordbaru(class="form-control is-invalid")}}
                                        
                                                 <div class="invalid-feedback">
                                                     {%for error in form.passwordbaru.errors %}
                                                     <span>{{error}}</span>
                                                     {% endfor %}
                                                 </div>
                                            {%else%}
                                                {{form.passwordbaru(class="form-control")}}
                                            
                                            {%endif%}
                                        </div>

                                        <div class="form-group">
                                            {{form.submit(class="btn btn-primary")}}
                                            <a class="btn btn-warning" href="{{url_for('gadmin.admin')}}">Kembali</a>
                                        </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
    
                            <!-- Input Kategori -->
                            <div class="col-xl-8 col-lg-7">
                                </div>
                                    <!-- Card Body -->
                                   
                        </div>
    
    </div></div>      
    
    </div>
                    <!-- /.container-fluid -->
{% endblock%}
    

wisata/templates/t_admin/editadatbudaya.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>Edit Data Adat & Kebudayaan</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control ")}}
            </div>
            <div class="form-group" id="editor">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.gambar.label(class="form-control-label")}}
                {{form.gambar(class="form-control ")}}
            </div>

            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>
            <a href="{{url_for('gadmin.admin_adatbudaya')}}" class="btn btn-danger"> Kembali</a>
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='keterangan') }}
    </div>
</div>


</div>
</div>
{%endblock%}

wisata/templates/t_admin/editsejarah.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>Edit Data Sejarah</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control ")}}
            </div>
            <div class="form-group" id="editor">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.gambar.label(class="form-control-label")}}
                {{form.gambar(class="form-control ")}}
            </div>

            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>
            <a href="{{url_for('gadmin.admin_sejarah')}}" class="btn btn-danger"> Kembali</a>
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='keterangan') }}
    </div>
</div>


</div>
</div>
{%endblock%}

wisata/templates/t_admin/editwisata.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>Edit Data Wisata</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama_wisata.label(class="form-control-label")}}
                {{form.nama_wisata(class="form-control ")}}
            </div>
            <div class="form-group" id="editor">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.lokasi.label(class="form-control-label")}}
                {{form.lokasi(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.foto.label(class="form-control-label")}}
                {{form.foto(class="form-control ")}}
            </div>

            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>
            <a href="{{url_for('gadmin.admin_wisata')}}" class="btn btn-danger"> Kembali</a>
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='keterangan') }}
    </div>
</div>


</div>
</div>
{%endblock%}

wisata/templates/t_admin/galery.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>input data galery</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.gambar.label(class="form-control-label")}}
                {{form.gambar(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>

        </form>

    </div>
</div>


</div>
</div>
{%endblock%}

wisata/templates/t_admin/login_admin.html
{% extends "t_admin/base_login.html" %}

{%block title%}
<h3 class="text-center">Login Admin</h3>
{%endblock title%}
{% block kontent %}
<h1>Login Admin</h1>
<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        {{form.username.label(class="form-control-label")}}
        {% if form.username.errors %}
        {{form.username(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
        {{form.username(class="form-control")}}
        {% endif %}
    </div>


    <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
        {{form.password(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
        {{form.password(class="form-control")}}
        {% endif %}
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary btn-sm")}}
    </div>
    <a class="btn btn-success btn-sm" style="margin-left: 80%; margin-top: -90px;"
        href="{{url_for('guser.home')}}">Back</a>

</form>


{% endblock%}

wisata/templates/t_admin/sejarah.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>Mengisi data Sejarah</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.gambar.label(class="form-control-label")}}
                {{form.gambar(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>

        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='keterangan') }}
    </div>
</div>


</div>
</div>
{%endblock%}

wisata/templates/t_admin/wisata.html
{% extends 't_admin/base.html'%}

{%block konten%}

<div class="container">
    <h1>Mengisi data wisata</h1>
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.nama_wisata.label(class="form-control-label")}}
                {{form.nama_wisata(class="form-control ")}}
            </div>
            <div class="form-group" id="editor">
                {{form.keterangan.label(class="form-control-label")}}
                {{form.keterangan(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.lokasi.label(class="form-control-label")}}
                {{form.lokasi(class="form-control ")}}
            </div>
            <div class="form-group">
                {{form.foto.label(class="form-control-label")}}
                {{form.foto(class="form-control ")}}
            </div>

            <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
            </div>

        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='keterangan') }}
    </div>
</div>


</div>
</div>
{%endblock%}